name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    uses: tingerrr/typst-test/.github/workflows/setup-B.yml@master
  tests:
    steps:
      - run: |
          just gen
          just test
