name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: tingerrr/hydra/.github/workflows/setup.yml@master
      - name: Run tests
        run: |
          just gen
          just test
