name: Tests
on:
  push:
    branches: [ master" ]
  pull_request:
    branches: [ master" ]

jobs:
  tests:
    steps:
      - uses: tingerrr/typst-test/.github/workflows/setup-B.yml@master
      - run: |
          just gen
          just test
