name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    uses: AnotherZane/hydra/.github/workflows/setup.yml@master
  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: |
          just gen
          just test
